# ==============================================
# Smart City Waste Management Mini Project
# Modules: Synthetic Data, Preprocessing, Modeling, Simulation, Visualization
# ==============================================

# -------------------------------
# Step 1: Install and Load Packages
# -------------------------------
# install.packages(c("dplyr","ggplot2","synthpop","e1071","rpart"))
library(dplyr)
library(ggplot2)
library(synthpop)
library(e1071)  # SVM
library(rpart)  # Decision Tree

# -------------------------------
# Step 2: Generate Synthetic Dataset
# -------------------------------
set.seed(123)
zones <- c("North","South","East","West")
real_data <- data.frame(
  Zone = as.factor(sample(zones, 500, replace = TRUE)),
  Population = sample(5000:15000, 500, replace = TRUE),
  Waste_Generated_kg = round(runif(500, 300, 8000), 1),
  Recycled_kg = round(runif(500, 100, 4000), 1),
  Organic_Percent = round(runif(500, 10, 90), 1),
  Plastic_Percent = round(runif(500, 5, 60), 1),
  Collection_Frequency = sample(1:7, 500, replace = TRUE),
  Smart_Bins_Used = as.factor(sample(c("Yes", "No"), 500, replace = TRUE)),
  Complaint_Count = sample(0:30, 500, replace = TRUE),
  Sensor_Failure_Rate = round(runif(500, 0.00, 0.25), 2)
)

synthetic_data <- syn(real_data)$syn
write.csv(synthetic_data, "synthetic_waste_mgmt_data.csv", row.names = FALSE)

# -------------------------------
# Step 3: Preprocessing
# -------------------------------
# Handling missing values (if any)
synthetic_data[is.na(synthetic_data)] <- 0

# Convert categorical variables to factors
synthetic_data$Zone <- as.factor(synthetic_data$Zone)
synthetic_data$Smart_Bins_Used <- as.factor(synthetic_data$Smart_Bins_Used)

# Normalize numeric columns
num_cols <- c("Population","Waste_Generated_kg","Recycled_kg",
              "Organic_Percent","Plastic_Percent","Collection_Frequency",
              "Complaint_Count","Sensor_Failure_Rate")
synthetic_data[num_cols] <- scale(synthetic_data[num_cols])

# -------------------------------
# Step 4: Visualize Raw vs Preprocessed Data
# -------------------------------
# Raw Data Example (before normalization)
raw_plot <- ggplot(real_data, aes(x=Zone, y=Waste_Generated_kg, fill=Zone)) +
  geom_bar(stat="summary", fun="mean") +
  labs(title="Raw Waste Generated by Zone", y="Average Waste (kg)") +
  theme_minimal()

# Preprocessed Data Example (after normalization)
pre_plot <- ggplot(synthetic_data, aes(x=Zone, y=Waste_Generated_kg, fill=Zone)) +
  geom_bar(stat="summary", fun="mean") +
  labs(title="Preprocessed Waste Generated by Zone", y="Normalized Waste") +
  theme_minimal()

# Comparison plot
compare_plot <- ggplot() +
  geom_bar(data=real_data, aes(x=Zone, y=Waste_Generated_kg, fill="Raw"), stat="summary", fun="mean", alpha=0.5, position="dodge") +
  geom_bar(data=synthetic_data, aes(x=Zone, y=Waste_Generated_kg, fill="Preprocessed"), stat="summary", fun="mean", alpha=0.5, position="dodge") +
  labs(title="Raw vs Preprocessed Waste by Zone", y="Value") +
  scale_fill_manual(values=c("Raw"="tomato","Preprocessed"="steelblue")) +
  theme_minimal()

# -------------------------------
# Step 5: Modeling
# -------------------------------
# Split data (here we use all for demo)
# Decision Tree Model to predict Zone based on waste features
dt_model <- rpart(Zone ~ Waste_Generated_kg + Recycled_kg + Organic_Percent + Plastic_Percent + Collection_Frequency,
                  data = synthetic_data, method="class")
cat("Decision Tree Summary:\n")
print(dt_model)
cat("\nPredictions Head:\n")
print(head(predict(dt_model, synthetic_data, type="class")))

# SVM Model
svm_model <- svm(Zone ~ Waste_Generated_kg + Recycled_kg + Organic_Percent + Plastic_Percent + Collection_Frequency,
                 data = synthetic_data)
cat("\nSVM Predictions Head:\n")
print(head(predict(svm_model, synthetic_data)))

# -------------------------------
# Step 6: Simulation (Discrete Event Simulation)
# -------------------------------
bins_per_zone <- 10
sim_days <- 7
steps_per_hour <- 4
hours_per_day <- 24
time_steps <- sim_days * hours_per_day * steps_per_hour
bin_capacity_kg <- 200
collect_threshold_pct <- 85
num_trucks <- 2
truck_service_time_min <- 8
avg_travel_time_min <- 10

# Initialize bins
bins <- data.frame(
  Zone = rep(zones, each=bins_per_zone),
  Bin_ID = 1:(bins_per_zone * length(zones)),
  Capacity_kg = bin_capacity_kg,
  Fill_kg = runif(bins_per_zone*length(zones), 0, 20),
  stringsAsFactors = FALSE
)
bins$Households <- rep(c(1200,800,1500,1000), each=bins_per_zone)/bins_per_zone
bins$WasteGen_kg_per_step <- (c(0.6,0.5,0.8,0.55)[match(bins$Zone,zones)] / (24*steps_per_hour)) * bins$Households

# Initialize trucks
trucks <- data.frame(Truck_ID=1:num_trucks, Available_at_step=rep(0,num_trucks))

events <- data.frame(Time=integer(0), Bin_ID=integer(0), Zone=character(0),
                     Truck_ID=integer(0), Fill_pct=numeric(0), stringsAsFactors=FALSE)

# Simulation Loop
for(t in 0:(time_steps-1)){
  noise <- rnorm(nrow(bins),1,0.15); noise[noise<0.5] <- 0.5
  bins$Fill_kg <- pmin(bins$Fill_kg + bins$WasteGen_kg_per_step*noise, bins$Capacity_kg)
  bins$Fill_pct <- round(100*bins$Fill_kg/bins$Capacity_kg,2)
  
  candidates <- bins %>% filter(Fill_pct >= collect_threshold_pct)
  free_trucks <- trucks %>% filter(Available_at_step <= t)
  
  if(nrow(free_trucks)>0 & nrow(candidates)>0){
    assign_n <- min(nrow(free_trucks), nrow(candidates))
    for(i in 1:assign_n){
      truck_id <- free_trucks$Truck_ID[i]; bin_id <- candidates$Bin_ID[i]
      total_min <- avg_travel_time_min + truck_service_time_min
      busy_steps <- ceiling(total_min/15)
      trucks$Available_at_step[trucks$Truck_ID==truck_id] <- t + busy_steps
      bins$Fill_kg[bins$Bin_ID==bin_id] <- 0; bins$Fill_pct[bins$Bin_ID==bin_id] <- 0
      events <- rbind(events, data.frame(Time=t, Bin_ID=bin_id, Zone=candidates$Zone[i],
                                         Truck_ID=truck_id, Fill_pct=candidates$Fill_pct[i]))
    }
  }
}

# -------------------------------
# Step 7: Simulation Summary + Bar Charts
# -------------------------------
zone_collections <- events %>% group_by(Zone) %>% summarise(Collections=n())
collections_by_time <- events %>% group_by(Time) %>% summarise(Collections=n())
top_times <- head(collections_by_time %>% arrange(desc(Collections)),10)
final_fill <- bins %>% group_by(Zone) %>% summarise(Average_Fill=mean(Fill_pct))

# Bar Charts
ggplot(zone_collections, aes(x=Zone, y=Collections, fill=Zone)) + geom_bar(stat="identity") +
  labs(title="Total Collections by Zone", x="Zone", y="Number of Collections") + theme_minimal()

ggplot(top_times, aes(x=factor(Time), y=Collections)) + geom_bar(stat="identity", fill="tomato") +
  labs(title="Top Time Steps by Collections", x="Time Step", y="Collections") + theme_minimal()

ggplot(final_fill, aes(x=Zone, y=Average_Fill, fill=Zone)) + geom_bar(stat="identity") +
  labs(title="Average Bin Fill by Zone (Final State)", x="Zone", y="Average Fill (%)") + theme_minimal()